# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "wl" ];
  #boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f1270ac5-c020-4aa4-9523-9d458a719119";
      fsType = "xfs";
    };

  #fileSystems."/boot" =
  #  { device = "/dev/disk/by-uuid/9351-57F5";
  #    fsType = "fat32";
  #  };

  #fileSystems."/boot" =
  #  { device = "/dev/disk/by-uuid/258b3b60-286b-4b4e-be7b-c4067a5841c4";
  #    fsType = "ext2";
  #  };

  #fileSystems."/zpool" =
  #  { device = "zpool";
  #    fsType = "zfs";
  #  };

  swapDevices = [ ];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # high-resolution display
}
